# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MediCareApp' do
  config = use_native_modules!

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  $FirebaseSDKVersion = '11.11.0'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MediCareAppTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end





# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, '15.0'
# prepare_react_native_project!
# use_modular_headers!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'MediCareApp' do
#   config = use_native_modules!

#   pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
#   pod 'FirebaseCoreInternal', :modular_headers => true
#   pod 'GoogleUtilities', :modular_headers => true
#   $FirebaseSDKVersion = '11.11.0'

#   use_react_native!(
#     :path => config[:reactNativePath],
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )


#   target 'MediCareAppTests' do
#     inherit! :complete
#     # Pods for testing
#   end


#   post_install do |installer|
#     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )

#     installer.pods_project.targets.each do |target|
#       target.build_configurations.each do |config|
#         # Force deployment target to 15.0 across all dependencies
#         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
#       end
#     end
#     installer.pods_project.targets.each do |target|
#       if target.name == 'ReactCommon'
#         target.build_configurations.each do |config|
#         config.build_settings['DEFINES_MODULE'] = 'NO'

#       end
#     end    
#   end
